### ISSUE TITLE
About 5-shot training

### ISSUE THREAD

**Issue by ghost** [pawn-sxy/DCAMA#1]
Hello !

Thanks for your exciting job ! I can test the model in 5-shot setting , but how can i train the model in 5-shot . It seems like this commit only provides codes for 1-shot training .

Thanks a lot .

**Comment by pawn-sxy** [comment]
We  reuse the 1-shot trained model for k-shot inference for computational efficiency, but it is also possible to train the model under 5-shot setting. 

If you want to do so, please refer to the "predict_mask_nshot()" method and change the calculation of logit_mask in "forward()" method, both of them are in DCAMA.py.

**Comment by ghost** [comment]
I know . Thanks for reply !

**Comment by bowen099** [comment]
您好，我是一个初学者，很抱歉这么久的项目打扰您。您提到为了高效完成任务，仅使用1shot进行训练，并用这个模型进行1shot或者5shot的测试。我有一个疑问，如果一您的经验来说这四种情况的miou指标是否可以大体排序为：5-shot 训练 + 5-shot 测试 > 1-shot 训练 + 5-shot 测试 > 1-shot 训练 + 1-shot 测试 > 5-shot 训练 + 1-shot 测试。
