### ISSUE TITLE
[Question] Considering 2D positional encoding?

### ISSUE THREAD

**Issue by sunziping2016** [pawn-sxy/DCAMA#11]
Hi!

Thanks for your excellent paper and clear code base. However, I'm curious about why you use 1D positional encoding after flattening the query & support features for multi-head attentions. I have the following 2 questions.
1. Have you ever considered using 2D positional encoding as defined in [tatp22/multidim-positional-encoding](https://github.com/tatp22/multidim-positional-encoding)?
2. Do you consider it a good idea?

Thanks!

---

您好！感谢你们提供了出色的论文和清晰的代码。不过，我有点好奇，你们为什么在将查询集和支撑集特征拍平后，使用了一维位置编码。我有以下两个问题：
1. 你们有没有考虑过使用二维位置编码，定义见[tatp22/multidim-positional-encoding](https://github.com/tatp22/multidim-positional-encoding)？
2. 你们觉得这是个好点子吗？

谢谢！

**Comment by pawn-sxy** [comment]
1. We have done the experiments but it didn't improve the performance.
2. It's a good idea but needs more experiments to find the best practice.
