### ISSUE TITLE
Pretrained swin backbone.

### ISSUE THREAD

**Issue by SirojbekSafarov** [pawn-sxy/DCAMA#2]
Hello!

Thank you for the great work. I cannot find swin 384 weights from the referenced link. If you have this weights can you provide.

Thanks.

**Comment by pawn-sxy** [comment]
Click the link in the 'Prepare backbones' section then the download should begin. The swin backbone we used is Swin-B pretrained on ImageNet-1K, reslotion is 384x384.

**Comment by SirojbekSafarov** [comment]
Thank you!

**Comment by pawn-sxy** [comment]
It works well for me. If the problem still exists, you can download the pre-trained swin backbone from the original repository[Swin-Transformer](https://github.com/microsoft/Swin-Transformer).
