### ISSUE TITLE
5-shot result

### ISSUE THREAD

**Issue by chenhao-zju** [pawn-sxy/DCAMA#4]
Thank you for your work, this is an excellent result!
But I can't reproduce the 5-shot in the paper, both with the model in GitHub or trained by myself.
I think maybe it's missing some detail.

![image](https://user-images.githubusercontent.com/62422590/190899593-a167a412-b8bc-490c-a051-2a4b2d788ee6.png)

![image](https://user-images.githubusercontent.com/62422590/190899679-74056d75-6d83-4c60-92aa-d49b653e2775.png)

**Comment by pawn-sxy** [comment]
The pretrained weight we offered is for COCO dataset, so it seems the '--bechmark' in test.sh should be 'COCO'. I will change it later.
