### ISSUE TITLE
Training HSNET with Swin Backbone

### ISSUE THREAD

**Issue by aminpdik** [pawn-sxy/DCAMA#8]
Thank you for your great work @pawn-sxy 

I am using your code to train HSNET (just changed the learner of HSNET with DCAMA in your code) with swin backbone, but the result is not well.  Could you please guide me to reproduce the same result that you reported for HSNET with swin backbone in your paper?

**Comment by pawn-sxy** [comment]
The pretrained Swin_B weight i used is 'swin_base_patch4_window12_384_22kto1k.pth', it is pre-trained under the Imagnet-22k and then trained on the imagenet-1k. It can be download here [https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window12_384_22kto1k.pth]. I have corrected the README in the hub.
